### ISSUE TITLE
Constantly asking for *OPC? without answer

### ISSUE THREAD

**Issue by dylangageot** [RoGeorge/DS1054Z_screen_capture#8]
Hi !

I'm trying to get a screenshot of my DS1054Z (04.04.SP1) with your script via my Raspberry Pi (connected with a RJ-45 cable to the scope), but when I execute the command "sudo python2 OscScreenGrabLAN.py 193.168.1.2", the program is stuck in a loop and it's seem to wait an answer according to the log.

The configuration of the Ethernet connection between my devices are correct and I tried to interface with the scope via a telnet client and it was working (*OPC? anwser 1, *IDN? give me information about my scope...). Ping also works.

I've downloaded the release version (1.0.0) and the master and both are giving to me this problem.

Do you have any idea of what is happening ?

Thanks in advance,
Naipsys.

[OscScreenGrabLAN.py.log.txt](https://github.com/RoGeorge/DS1054Z_screen_capture/files/684897/OscScreenGrabLAN.py.log.txt)

EDIT : I've tested on my PC under Windows 10, same issues.

**Comment by RoGeorge** [comment]
For your firmware version, I guess all the SCPI commands must end with \n.
A few minutes ago I pushed a new commit that should fix this.

Please be advised that there are some other known bugs for CSV download of raw memory. Those were not fixed because the script was re-written in order to get rid of telnet and other Python dependencies, and it will be pushed as v2.0 as soon as it will be in a working state.

**Comment by dylangageot** [comment]
That's work for png after upgrade the script for the one that you've maked, the only format that I've tested, thanks!
